load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
  name = "pyaoc2024",
  srcs = ["pyaoc2024.py"],
  data = [
    "aoc2024day01example.txt",
    "aoc2024day01input.txt",
    "aoc2024day02example.txt",
    "aoc2024day02input.txt",
  ],
)
